/*
Copyright 2026 mylonics
Author Rijesh Augustine
SPDX-License-Identifier: Apache-2.0
*/

/**
 * Helpers shared by the Build Dashboard's Kconfig editor.
 *
 * Responsible for serializing the user's edits as a Kconfig fragment file
 * (`CONFIG_FOO=value` / `# CONFIG_FOO is not set` lines), merging changes
 * into existing conf files (e.g. prj.conf), offering to register the saved
 * file as an EXTRA_CONF_FILE on the active build, and enumerating the
 * available save targets from build_info.yml + confFiles.
 */

import * as fs from "fs-extra";
import * as path from "upath";
import * as vscode from "vscode";

import { ConfigFiles, mergeConfigFiles } from "../../project_utilities/config_selector";
import { getProjectFolder, getBuildFolder, ProjectConfig } from "../../project_utilities/project";
import { BuildConfig } from "../../project_utilities/build_selector";
import { loadYamlFile } from "../../utilities/utils";
import { setWorkspaceState } from "../../setup_utilities/state-management";
import type { WorkspaceConfig } from "../../setup_utilities/types";
import type { KconfigChange, KconfigSaveTarget } from "./DashboardPanel";

/**
 * Render the user's edits as a Kconfig fragment.  Bool symbols use the
 * canonical "CONFIG_X=y" / "# CONFIG_X is not set" forms; other types are
 * written as "CONFIG_X=value" with strings double-quoted.
 */
export function renderFragment(changes: KconfigChange[]): string {
  const out: string[] = [
    "# Generated by Zephyr IDE Build Dashboard.",
    "# This file contains only the symbols you edited \u2014 add it to the build's",
    "# EXTRA_CONF_FILE list (or merge into prj.conf) for the values to take effect.",
    "",
  ];
  for (const c of changes) {
    if (!/^CONFIG_[A-Za-z0-9_]+$/.test(c.name)) { continue; }
    const t = c.type;
    if (t === "bool" || t === "tristate") {
      const v = c.value.trim().toLowerCase();
      if (v === "y" || v === "m") {
        out.push(`${c.name}=${v}`);
      } else {
        // Canonical "n" representation in Kconfig fragments.
        out.push(`# ${c.name} is not set`);
      }
    } else if (t === "int" || t === "hex") {
      out.push(`${c.name}=${c.value.trim()}`);
    } else {
      // string (default): always quote, escape embedded quotes/backslashes.
      const escaped = c.value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      out.push(`${c.name}="${escaped}"`);
    }
  }
  out.push("");
  return out.join("\n");
}

/**
 * Prompts the user for a save location, writes the fragment, and returns
 * the absolute path on success.  Default location is the project folder
 * with filename `prj_dashboard.conf`.
 */
export async function saveFragmentInteractive(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  changes: KconfigChange[],
): Promise<string | undefined> {
  const defaultDir = getProjectFolder(wsConfig, project);
  const defaultUri = vscode.Uri.file(path.join(defaultDir, "prj_dashboard.conf"));
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { "Kconfig fragment": ["conf"] },
    saveLabel: "Save Kconfig Fragment",
    title: "Save Kconfig fragment from Dashboard",
  });
  if (!target) { return undefined; }
  await fs.outputFile(target.fsPath, renderFragment(changes), "utf8");
  return target.fsPath;
}

/**
 * Asks the user whether to register the saved fragment as an EXTRA_CONF_FILE
 * on the given build.  Returns true if the build state was modified.
 *
 * The fragment is stored as a workspace-relative path so it matches how
 * `configSelector` adds files via the existing UI.
 */
export async function offerAddFragmentToBuild(
  context: vscode.ExtensionContext,
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  fragmentAbsPath: string,
): Promise<boolean> {
  const rel = path.relative(wsConfig.rootPath, fragmentAbsPath);
  // If already registered (override or extra) on the build, skip the prompt.
  if (build.confFiles.config.some((c: { path: string }) => path.normalize(c.path) === path.normalize(rel))) {
    void vscode.window.showInformationMessage(
      `Kconfig fragment saved to ${rel} (already attached to build "${build.name}").`,
    );
    return false;
  }
  const choice = await vscode.window.showInformationMessage(
    `Saved Kconfig fragment to ${rel}. Add it to build "${build.name}" as an Extra Conf File?`,
    { modal: false },
    "Add to Build",
    "Skip",
  );
  if (choice !== "Add to Build") { return false; }

  const addition: ConfigFiles = {
    config: [{ path: rel, extra: true }],
    overlay: [],
  };
  mergeConfigFiles(build.confFiles, addition);
  await setWorkspaceState(context, wsConfig);
  void vscode.window.showInformationMessage(
    `Added ${rel} to build "${build.name}" as EXTRA_CONF_FILE.`,
  );
  return true;
}

/**
 * Attach a conf fragment to the project's or build's confFiles list as an
 * EXTRA_CONF_FILE.  Does not prompt — the scope was already chosen by the
 * user in the Save menu.  Skips silently if the path is already registered.
 */
export async function attachFragmentToScope(
  context: vscode.ExtensionContext,
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  fragmentAbsPath: string,
  scope: "build" | "project",
): Promise<void> {
  const rel = path.relative(wsConfig.rootPath, fragmentAbsPath);
  const targetFiles = scope === "build" ? build.confFiles.config : project.confFiles.config;
  if (targetFiles.some((c) => path.normalize(c.path) === path.normalize(rel))) {
    // Already registered — nothing to do.
    return;
  }
  const addition: ConfigFiles = {
    config: [{ path: rel, extra: true }],
    overlay: [],
  };
  if (scope === "build") {
    mergeConfigFiles(build.confFiles, addition);
  } else {
    mergeConfigFiles(project.confFiles, addition);
  }
  await setWorkspaceState(context, wsConfig);
}

/**
 * Parse a Kconfig conf/fragment file into a map of symbol name → raw value
 * line (the full "CONFIG_X=value" or "# CONFIG_X is not set" line is kept
 * for round-trip fidelity on unmodified entries).
 *
 * Returns an array of lines in order, where each element is either
 * `{ sym: name, line: "CONFIG_X=val" }` for a known symbol line or
 * `{ sym: null, line: "..." }` for a comment / blank / unknown line.
 */
interface ParsedLine { sym: string | null; line: string; }

function parseConfFile(content: string): ParsedLine[] {
  const out: ParsedLine[] = [];
  for (const raw of content.split(/\r?\n/)) {
    const notSet = raw.match(/^#\s*(CONFIG_[A-Za-z0-9_]+)\s+is not set\s*$/);
    if (notSet) {
      out.push({ sym: notSet[1], line: raw });
      continue;
    }
    const assign = raw.match(/^(CONFIG_[A-Za-z0-9_]+)=/);
    if (assign) {
      out.push({ sym: assign[1], line: raw });
      continue;
    }
    out.push({ sym: null, line: raw });
  }
  return out;
}

/**
 * Render a single symbol change as a Kconfig fragment line.
 * Mirrors the logic in renderFragment but for a single entry.
 */
function renderLine(c: KconfigChange): string {
  if (!/^CONFIG_[A-Za-z0-9_]+$/.test(c.name)) { return ""; }
  const t = c.type;
  if (t === "bool" || t === "tristate") {
    const v = c.value.trim().toLowerCase();
    return (v === "y" || v === "m") ? `${c.name}=${v}` : `# ${c.name} is not set`;
  } else if (t === "int" || t === "hex") {
    return `${c.name}=${c.value.trim()}`;
  } else {
    const escaped = c.value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `${c.name}="${escaped}"`;
  }
}

/**
 * Merge Kconfig changes into an existing conf file's content (string).
 *
 * - Symbols already present in the file have their line replaced in-place.
 * - New symbols are appended at the end.
 * - Lines for symbols NOT in the change set are preserved unchanged.
 *
 * Returns the merged content string.
 */
export function mergeFragmentContent(existing: string, changes: KconfigChange[]): string {
  const parsed = parseConfFile(existing);
  const byName = new Map<string, KconfigChange>();
  for (const c of changes) {
    if (/^CONFIG_[A-Za-z0-9_]+$/.test(c.name)) { byName.set(c.name, c); }
  }

  const applied = new Set<string>();
  const merged: string[] = [];

  for (const { sym, line } of parsed) {
    if (sym && byName.has(sym)) {
      merged.push(renderLine(byName.get(sym)!));
      applied.add(sym);
    } else {
      merged.push(line);
    }
  }

  // Strip trailing empty line that parseConfFile may have generated
  while (merged.length > 0 && merged[merged.length - 1] === "") { merged.pop(); }

  // Append new symbols not yet in the file
  const appended: string[] = [];
  for (const [name, c] of byName) {
    if (!applied.has(name)) {
      appended.push(renderLine(c));
    }
  }
  if (appended.length > 0) {
    merged.push(""); // blank separator
    merged.push(...appended);
  }
  merged.push("");
  return merged.join("\n");
}

/**
 * Build the list of save targets available in the Save menu.
 *
 * Priority order:
 *   1. confFiles entries (build-scope first, then project-scope).
 *   2. Auto-detected entries from build_info.yml (cmake.kconfig.files +
 *      user-files) that are inside the workspace root and outside the
 *      build folder.  Board/arch/module files that live outside the
 *      workspace are silently excluded.
 *
 * Each entry carries a `kind` ("extra" | "override" | "auto") and an
 * `attached` flag indicating whether it is already tracked in confFiles.
 *
 * When build_info.yml is not present (no build yet) the function falls
 * back to the confFiles-only enumeration so the menu still works.
 */
export function listSaveTargets(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
): KconfigSaveTarget[] {
  const isConfFile = (p: string) => /\.conf$/i.test(p);
  const buildFolder = path.normalize(getBuildFolder(wsConfig, project, build));
  const rootNorm = path.normalize(wsConfig.rootPath);

  const seen = new Set<string>(); // normalised absolute paths already added
  const out: KconfigSaveTarget[] = [];

  /** Push one entry, deduplicating by absolute path. */
  const push = (
    relPath: string,
    absPath: string,
    scope: "build" | "project",
    kind: "extra" | "override" | "auto",
    attached: boolean,
  ) => {
    const norm = path.normalize(absPath).toLowerCase();
    if (seen.has(norm)) { return; }
    seen.add(norm);
    out.push({
      path: relPath,
      absPath,
      scope,
      kind,
      attached,
      exists: fs.existsSync(absPath),
    });
  };

  // ── 1. Entries already known to the extension (confFiles) ──────────────
  for (const e of build.confFiles.config) {
    if (!isConfFile(e.path)) { continue; }
    const abs = path.resolve(wsConfig.rootPath, e.path);
    push(e.path, abs, "build", e.extra ? "extra" : "override", true);
  }
  for (const e of project.confFiles.config) {
    if (!isConfFile(e.path)) { continue; }
    const abs = path.resolve(wsConfig.rootPath, e.path);
    push(e.path, abs, "project", e.extra ? "extra" : "override", true);
  }

  // ── 2. Auto-detected entries from build_info.yml ────────────────────────
  // getBuildInfo is synchronous-ish (reads yaml) — we call the sync variant
  // via the already-loaded module.
  const buildInfoPath = path.join(buildFolder, "build_info.yml");
  if (fs.existsSync(buildInfoPath)) {
    // Collect all kconfig source files west fed into this build.
    let kconfigFiles: string[] = [];
    try {
      const parsed = loadYamlFile(buildInfoPath);
      if (parsed?.cmake?.kconfig) {
        kconfigFiles = [
          ...(parsed.cmake.kconfig["files"] ?? []),
          ...(parsed.cmake.kconfig["user-files"] ?? []),
        ];
      }
    } catch {
      // build_info.yml unreadable — skip auto-detection.
    }

    for (const absStr of kconfigFiles) {
      const absNorm = path.normalize(absStr);
      // Exclude generated files inside the build folder.
      if (absNorm.toLowerCase().startsWith(buildFolder.toLowerCase())) { continue; }
      // Exclude files outside the workspace root (board/arch/module files
      // from the Zephyr tree or SDK that the user should not edit here).
      if (!absNorm.toLowerCase().startsWith(rootNorm.toLowerCase())) { continue; }
      // Only .conf files are editable fragments.
      if (!isConfFile(absNorm)) { continue; }

      const rel = path.relative(wsConfig.rootPath, absNorm);
      // Determine kind by checking whether the file is in confFiles.
      // If it's already in confFiles it was already pushed in step 1 and
      // will be deduped by `push`; the kind/attached were already set.
      // If it's not in confFiles it is auto-detected.
      const normLower = absNorm.toLowerCase();
      const matchedBuildEntry = build.confFiles.config.find(
        (e) => path.normalize(path.resolve(wsConfig.rootPath, e.path)).toLowerCase() === normLower,
      );
      const matchedProjEntry = project.confFiles.config.find(
        (e) => path.normalize(path.resolve(wsConfig.rootPath, e.path)).toLowerCase() === normLower,
      );
      const attached = !!(matchedBuildEntry ?? matchedProjEntry);
      const autoScope: "build" | "project" = matchedBuildEntry ? "build" : "project";
      const kind: "extra" | "override" | "auto" = attached
        ? ((matchedBuildEntry ?? matchedProjEntry)!.extra ? "extra" : "override")
        : "auto";
      push(rel, path.normalize(absNorm), autoScope, kind, attached);
    }
  }

  return out;
}

/**
 * Save Kconfig changes to a target conf file.
 *
 * Behaviour (same for new files and existing ones):
 *   - If the file already exists, each symbol is looked up in the file:
 *       • Found  → the existing line is replaced with the new value.
 *       • Not found → the entry is appended at the end.
 *   - If the file does not yet exist every entry is simply appended
 *     (which is equivalent to creating it from scratch).
 *
 * When `opts.symbols` is provided only those named symbols are written;
 * all other changes in the session are ignored.  This powers the per-row
 * "Save this symbol to…" context-menu action.
 *
 * The session's `writeFragment` callback is always used to obtain
 * canonically-encoded values (kconfiglib's write_min_config format) before
 * merging so bool "n" values appear as `# CONFIG_X is not set`.
 *
 * Uses a temp-file + rename for atomicity.
 */
export async function saveSessionFragmentToPath(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  absPath: string,
  writeFragment: (path: string) => Promise<unknown>,
  opts: { symbols?: string[] } = {},
): Promise<string | undefined> {
  if (!absPath) { return undefined; }
  // Defence-in-depth: only allow paths that appear in the picker.
  const allowed = listSaveTargets(wsConfig, project, build);
  const match = allowed.find(
    (t) => path.normalize(t.absPath).toLowerCase()
      === path.normalize(absPath).toLowerCase(),
  );
  if (!match) {
    throw new Error(`Refusing to save: ${absPath} is not a known Kconfig conf file for this build.`);
  }

  await fs.ensureDir(path.dirname(absPath));
  const tmp = `${absPath}.tmp-${process.pid}-${Date.now()}`;

  // Best-effort single-revision backup so the user can revert manually.
  try {
    if (await fs.pathExists(absPath)) {
      await fs.copy(absPath, `${absPath}.bak`, { overwrite: true });
    }
  } catch { /* backup failure must never block the save */ }

  const sessionTmp = `${absPath}.session-${process.pid}-${Date.now()}`;
  try {
    // 1. Ask kconfiglib to write the minimal fragment so we get canonical
    //    encoding (e.g. `# CONFIG_X is not set` for disabled bools).
    await writeFragment(sessionTmp);

    // 2. Parse the session output to build the change list.
    let sessionContent = "";
    try { sessionContent = await fs.readFile(sessionTmp, "utf8"); } catch { /* empty */ }
    const sessionLines = parseConfFile(sessionContent);
    const sessionChanges: KconfigChange[] = [];
    for (const { sym, line } of sessionLines) {
      if (!sym) { continue; }
      const notSet = /^#\s*CONFIG_[A-Za-z0-9_]+\s+is not set/.test(line);
      const assign = line.match(/^CONFIG_[A-Za-z0-9_]+=(.*)/);
      const rawValue = assign ? assign[1] : "";
      // Detect type from the raw value written by kconfiglib:
      //   bool/tristate: unquoted "y" or "m"
      //   string: double-quoted value
      //   int/hex: everything else (0x…, decimal, etc.)
      const isQuotedString = rawValue.startsWith('"') && rawValue.endsWith('"') && rawValue.length >= 2;
      const type: string = notSet ? "bool"
        : (rawValue === "y" || rawValue === "m") ? "bool"
          : isQuotedString ? "string"
            : "int";
      const value = notSet ? "n" : rawValue.replace(/^"(.*)"$/, "$1");
      sessionChanges.push({ name: sym, value, type });
    }

    // 3. Apply symbol filter (for per-row single-symbol saves).
    const changes = opts.symbols
      ? sessionChanges.filter((c) => opts.symbols!.includes(c.name))
      : sessionChanges;

    // 4. Read the existing file content (empty string for new files).
    let existing = "";
    try { existing = await fs.readFile(absPath, "utf8"); } catch { /* new file — start empty */ }

    // 5. Merge: update existing symbol lines in-place, append new ones at end.
    const merged = mergeFragmentContent(existing, changes);

    // 6. Write atomically.
    await fs.outputFile(tmp, merged, "utf8");
    await fs.move(tmp, absPath, { overwrite: true });
  } finally {
    try { await fs.remove(sessionTmp); } catch { /* ignore */ }
    try {
      if (await fs.pathExists(tmp)) { await fs.remove(tmp); }
    } catch { /* ignore */ }
  }
  return absPath;
}
