/*
Copyright 2026 mylonics
Author Rijesh Augustine
SPDX-License-Identifier: Apache-2.0
*/

/**
 * Helpers shared by the Build Dashboard's Kconfig editor (Phase 1A).
 *
 * Responsible for serializing the user's edits as a Kconfig fragment file
 * (`CONFIG_FOO=value` / `# CONFIG_FOO is not set` lines) and offering to
 * register the saved file as an EXTRA_CONF_FILE on the active build via
 * the existing `confFiles` plumbing in `project_utilities/config_selector`.
 */

import * as fs from "fs-extra";
import * as path from "upath";
import * as vscode from "vscode";

import { ConfigFiles, mergeConfigFiles } from "../../project_utilities/config_selector";
import { getProjectFolder, ProjectConfig } from "../../project_utilities/project";
import { BuildConfig } from "../../project_utilities/build_selector";
import { setWorkspaceState } from "../../setup_utilities/state-management";
import type { WorkspaceConfig } from "../../setup_utilities/types";
import type { KconfigChange, KconfigSaveTarget } from "./DashboardPanel";

/**
 * Render the user's edits as a Kconfig fragment.  Bool symbols use the
 * canonical "CONFIG_X=y" / "# CONFIG_X is not set" forms; other types are
 * written as "CONFIG_X=value" with strings double-quoted.
 */
export function renderFragment(changes: KconfigChange[]): string {
  const out: string[] = [
    "# Generated by Zephyr IDE Build Dashboard.",
    "# This file contains only the symbols you edited \u2014 add it to the build's",
    "# EXTRA_CONF_FILE list (or merge into prj.conf) for the values to take effect.",
    "",
  ];
  for (const c of changes) {
    if (!/^CONFIG_[A-Za-z0-9_]+$/.test(c.name)) { continue; }
    const t = c.type;
    if (t === "bool" || t === "tristate") {
      const v = c.value.trim().toLowerCase();
      if (v === "y" || v === "m") {
        out.push(`${c.name}=${v}`);
      } else {
        // Canonical "n" representation in Kconfig fragments.
        out.push(`# ${c.name} is not set`);
      }
    } else if (t === "int" || t === "hex") {
      out.push(`${c.name}=${c.value.trim()}`);
    } else {
      // string (default): always quote, escape embedded quotes/backslashes.
      const escaped = c.value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      out.push(`${c.name}="${escaped}"`);
    }
  }
  out.push("");
  return out.join("\n");
}

/**
 * Prompts the user for a save location, writes the fragment, and returns
 * the absolute path on success.  Default location is the project folder
 * with filename `prj_dashboard.conf`.
 */
export async function saveFragmentInteractive(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  changes: KconfigChange[],
): Promise<string | undefined> {
  const defaultDir = getProjectFolder(wsConfig, project);
  const defaultUri = vscode.Uri.file(path.join(defaultDir, "prj_dashboard.conf"));
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { "Kconfig fragment": ["conf"] },
    saveLabel: "Save Kconfig Fragment",
    title: "Save Kconfig fragment from Dashboard",
  });
  if (!target) { return undefined; }
  await fs.outputFile(target.fsPath, renderFragment(changes), "utf8");
  return target.fsPath;
}

/**
 * Asks the user whether to register the saved fragment as an EXTRA_CONF_FILE
 * on the given build.  Returns true if the build state was modified.
 *
 * The fragment is stored as a workspace-relative path so it matches how
 * `configSelector` adds files via the existing UI.
 */
export async function offerAddFragmentToBuild(
  context: vscode.ExtensionContext,
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  fragmentAbsPath: string,
): Promise<boolean> {
  const rel = path.relative(wsConfig.rootPath, fragmentAbsPath);
  // If already registered (override or extra) on the build, skip the prompt.
  if (build.confFiles.config.some((c: { path: string }) => path.normalize(c.path) === path.normalize(rel))) {
    void vscode.window.showInformationMessage(
      `Kconfig fragment saved to ${rel} (already attached to build "${build.name}").`,
    );
    return false;
  }
  const choice = await vscode.window.showInformationMessage(
    `Saved Kconfig fragment to ${rel}. Add it to build "${build.name}" as an Extra Conf File?`,
    { modal: false },
    "Add to Build",
    "Skip",
  );
  if (choice !== "Add to Build") { return false; }

  const addition: ConfigFiles = {
    config: [{ path: rel, extra: true }],
    overlay: [],
  };
  mergeConfigFiles(build.confFiles, addition);
  await setWorkspaceState(context, wsConfig);
  void vscode.window.showInformationMessage(
    `Added ${rel} to build "${build.name}" as EXTRA_CONF_FILE.`,
  );
  return true;
}

/**
 * Build the list of pre-existing extra Kconfig fragments attached to either
 * the build (preferred) or the project that the dashboard's Save menu can
 * overwrite.  Only `.conf` entries with `extra=true` are included; override
 * entries (prj.conf) are deliberately left out so the user cannot accidentally
 * blow away a hand-maintained main configuration with a minimal fragment.
 *
 * Build-scope entries shadow project-scope entries with the same path so each
 * relative path appears at most once.
 */
export function listSaveTargets(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
): KconfigSaveTarget[] {
  const isFragment = (p: string) => /\.conf$/i.test(p);
  const seen = new Set<string>();
  const out: KconfigSaveTarget[] = [];

  const push = (entryPath: string, scope: "build" | "project") => {
    const norm = path.normalize(entryPath);
    if (seen.has(norm)) { return; }
    seen.add(norm);
    const absPath = path.resolve(wsConfig.rootPath, entryPath);
    out.push({
      path: entryPath,
      absPath,
      scope,
      exists: fs.existsSync(absPath),
    });
  };

  for (const e of build.confFiles.config) {
    if (e.extra && isFragment(e.path)) { push(e.path, "build"); }
  }
  for (const e of project.confFiles.config) {
    if (e.extra && isFragment(e.path)) { push(e.path, "project"); }
  }
  return out;
}

/**
 * Overwrite an existing extra-fragment file with the (minimal) Kconfig output
 * produced by `writeFragment`.  Uses a temp-file + rename for atomicity so a
 * crash mid-write cannot leave the build with a half-written fragment.
 *
 * Skips the "attach to build" prompt because the path is already attached
 * (the picker only offers paths from `listSaveTargets`).
 */
export async function saveSessionFragmentToPath(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  absPath: string,
  writeFragment: (path: string) => Promise<unknown>,
): Promise<string | undefined> {
  if (!absPath) { return undefined; }
  // Defence-in-depth: only allow paths that actually appear in the picker.
  const allowed = listSaveTargets(wsConfig, project, build);
  const match = allowed.find(
    (t) => path.normalize(t.absPath).toLowerCase()
      === path.normalize(absPath).toLowerCase(),
  );
  if (!match) {
    throw new Error(`Refusing to save: ${absPath} is not an attached extra Kconfig fragment for this build.`);
  }
  await fs.ensureDir(path.dirname(absPath));
  // kconfiglib's write_min_config writes directly; route through a temp file
  // so we can rename atomically.
  const tmp = `${absPath}.tmp-${process.pid}-${Date.now()}`;
  try {
    await writeFragment(tmp);
    await fs.move(tmp, absPath, { overwrite: true });
  } finally {
    if (await fs.pathExists(tmp)) { try { await fs.remove(tmp); } catch { /* ignore */ } }
  }
  return absPath;
}
