/*
Copyright 2026 mylonics
Author Rijesh Augustine
SPDX-License-Identifier: Apache-2.0
*/

/**
 * Helpers shared by the Build Dashboard's Kconfig editor (Phase 1A).
 *
 * Responsible for serializing the user's edits as a Kconfig fragment file
 * (`CONFIG_FOO=value` / `# CONFIG_FOO is not set` lines) and offering to
 * register the saved file as an EXTRA_CONF_FILE on the active build via
 * the existing `confFiles` plumbing in `project_utilities/config_selector`.
 */

import * as fs from "fs-extra";
import * as path from "upath";
import * as vscode from "vscode";

import { ConfigFiles, mergeConfigFiles } from "../../project_utilities/config_selector";
import { getProjectFolder, ProjectConfig } from "../../project_utilities/project";
import { BuildConfig } from "../../project_utilities/build_selector";
import { setWorkspaceState } from "../../setup_utilities/state-management";
import type { WorkspaceConfig } from "../../setup_utilities/types";
import type { KconfigChange } from "./DashboardPanel";

/**
 * Render the user's edits as a Kconfig fragment.  Bool symbols use the
 * canonical "CONFIG_X=y" / "# CONFIG_X is not set" forms; other types are
 * written as "CONFIG_X=value" with strings double-quoted.
 */
export function renderFragment(changes: KconfigChange[]): string {
  const out: string[] = [
    "# Generated by Zephyr IDE Build Dashboard.",
    "# This file contains only the symbols you edited \u2014 add it to the build's",
    "# EXTRA_CONF_FILE list (or merge into prj.conf) for the values to take effect.",
    "",
  ];
  for (const c of changes) {
    if (!/^CONFIG_[A-Za-z0-9_]+$/.test(c.name)) { continue; }
    const t = c.type;
    if (t === "bool" || t === "tristate") {
      const v = c.value.trim().toLowerCase();
      if (v === "y" || v === "m") {
        out.push(`${c.name}=${v}`);
      } else {
        // Canonical "n" representation in Kconfig fragments.
        out.push(`# ${c.name} is not set`);
      }
    } else if (t === "int" || t === "hex") {
      out.push(`${c.name}=${c.value.trim()}`);
    } else {
      // string (default): always quote, escape embedded quotes/backslashes.
      const escaped = c.value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      out.push(`${c.name}="${escaped}"`);
    }
  }
  out.push("");
  return out.join("\n");
}

/**
 * Prompts the user for a save location, writes the fragment, and returns
 * the absolute path on success.  Default location is the project folder
 * with filename `prj_dashboard.conf`.
 */
export async function saveFragmentInteractive(
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  changes: KconfigChange[],
): Promise<string | undefined> {
  const defaultDir = getProjectFolder(wsConfig, project);
  const defaultUri = vscode.Uri.file(path.join(defaultDir, "prj_dashboard.conf"));
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { "Kconfig fragment": ["conf"] },
    saveLabel: "Save Kconfig Fragment",
    title: "Save Kconfig fragment from Dashboard",
  });
  if (!target) { return undefined; }
  await fs.outputFile(target.fsPath, renderFragment(changes), "utf8");
  return target.fsPath;
}

/**
 * Asks the user whether to register the saved fragment as an EXTRA_CONF_FILE
 * on the given build.  Returns true if the build state was modified.
 *
 * The fragment is stored as a workspace-relative path so it matches how
 * `configSelector` adds files via the existing UI.
 */
export async function offerAddFragmentToBuild(
  context: vscode.ExtensionContext,
  wsConfig: WorkspaceConfig,
  project: ProjectConfig,
  build: BuildConfig,
  fragmentAbsPath: string,
): Promise<boolean> {
  const rel = path.relative(wsConfig.rootPath, fragmentAbsPath);
  // If already registered (override or extra) on the build, skip the prompt.
  if (build.confFiles.config.some((c: { path: string }) => path.normalize(c.path) === path.normalize(rel))) {
    void vscode.window.showInformationMessage(
      `Kconfig fragment saved to ${rel} (already attached to build "${build.name}").`,
    );
    return false;
  }
  const choice = await vscode.window.showInformationMessage(
    `Saved Kconfig fragment to ${rel}. Add it to build "${build.name}" as an Extra Conf File?`,
    { modal: false },
    "Add to Build",
    "Skip",
  );
  if (choice !== "Add to Build") { return false; }

  const addition: ConfigFiles = {
    config: [{ path: rel, extra: true }],
    overlay: [],
  };
  mergeConfigFiles(build.confFiles, addition);
  await setWorkspaceState(context, wsConfig);
  void vscode.window.showInformationMessage(
    `Added ${rel} to build "${build.name}" as EXTRA_CONF_FILE.`,
  );
  return true;
}
