// Zephyr IDE Setup Panel Client-Side Logic

const vscode = acquireVsCodeApi();

// State tracking for host tools installation
const hostToolsInstallationState = {
    inProgress: false,
    packageStates: {} // Store state for each package (installing, pending-restart, etc.)
};

// State tracking for workspace setup progress
/** True while a workspace setup operation is actively in progress. */
let _workspaceSetupActive = false;
/** Timer handle used to auto-dismiss the completed progress banner. */
let _setupProgressDismissTimer = null;

// Navigation Functions
function navigateToSubPage(page) {
    vscode.postMessage({
        command: 'navigateToPage',
        page: page
    });
}

function navigateToOverview() {
    vscode.postMessage({
        command: 'navigateToPage',
        page: 'overview'
    });
}

// Auto-navigate to a specific page if the extension requested it
// (e.g. after updateContent replaces all HTML during workspace setup).
(function autoNavigate() {
    var page = document.body.getAttribute('data-auto-navigate');
    if (page) {
        navigateToSubPage(page);
    }
})();

// Listen for messages from the extension
window.addEventListener('message', event => {
    const message = event.data;

    switch (message.command) {
        case 'showSubPage':
            showSubPage(message.content, message.page);
            break;
        case 'showOverview':
            showOverview();
            break;
        case 'sdkListResult':
            displaySDKList(message.data);
            break;
        case 'updateHostToolsStatus':
            updateHostToolsStatus(message.data, message.error);
            break;
        case 'hostToolsStartInstallAll':
            handleHostToolsStartInstallAll();
            break;
        case 'hostToolsInstallAllStarted':
            handleHostToolsInstallAllStarted(message.total);
            break;
        case 'hostToolsPackageInstalling':
            handleHostToolsPackageInstalling(message.packageName, message.current, message.total);
            break;
        case 'hostToolsPackageInstalled':
            handleHostToolsPackageInstalled(message.packageName, message.success, message.pendingRestart, message.current, message.total);
            break;
        case 'hostToolsInstallAllComplete':
            handleHostToolsInstallAllComplete(message.needsRestart, message.hasErrors);
            break;
        case 'westYmlContent':
            loadWestYmlContent(message.content);
            break;
        case 'workspaceSetupProgress':
            handleWorkspaceSetupProgress(message.data);
            break;
    }
});

/**
 * Escapes HTML to prevent XSS attacks
 * @param {string} text - Text to escape
 * @returns {string} - Escaped text
 */
function escapeHtml(text) {
    // Handle null, undefined, or non-string inputs
    if (text == null || typeof text !== 'string') {
        return '';
    }
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function showSubPage(content, page) {
    const overviewContainer = document.getElementById('overviewContainer');
    const subPageContainer = document.getElementById('subPageContainer');

    if (overviewContainer && subPageContainer) {
        // Hide overview and show sub-page
        overviewContainer.classList.add('hidden');

        // Use DOMParser to safely parse HTML content from trusted server-side source
        // Content is generated by TypeScript classes (HostToolsSubPage, SDKSubPage, WorkspaceSubPage)
        // which only use configuration values, not user input
        const parser = new DOMParser();
        const doc = parser.parseFromString(content, 'text/html');
        const subPageContent = doc.body.firstChild;

        // Clear and append the parsed content
        subPageContainer.innerHTML = '';
        if (subPageContent) {
            subPageContainer.appendChild(subPageContent);
        }

        subPageContainer.classList.add('visible');

        // If a workspace setup is in progress and we just rendered the workspace
        // page, switch to the initializing state so the user never sees a flash
        // of the "Workspace Ready" or "Setup Required" content.
        if (page === 'workspace' && _workspaceSetupActive) {
            setWorkspaceState('initializing');
        }
    }
}

function hideSubPage() {
    const overviewContainer = document.getElementById('overviewContainer');
    const subPageContainer = document.getElementById('subPageContainer');

    if (overviewContainer && subPageContainer) {
        // Show overview and hide sub-page
        subPageContainer.classList.remove('visible');
        overviewContainer.classList.remove('hidden');

        // Reset the active setup flag when navigating away so stale state
        // does not interfere if the user later revisits the workspace page.
        _workspaceSetupActive = false;

        // Clear sub-page content after animation
        setTimeout(() => {
            subPageContainer.innerHTML = '';
        }, 300);
    }
}

function showOverview() {
    hideSubPage();
}

// Section Toggle Functions (kept for compatibility)
function toggleSection(sectionId) {
    const content = document.getElementById(sectionId + 'Content');
    const icon = document.getElementById(sectionId + 'Icon');

    if (content.classList.contains('expanded')) {
        content.classList.remove('expanded');
        icon.classList.remove('expanded');
    } else {
        content.classList.add('expanded');
        icon.classList.add('expanded');
    }
}

// Scroll to section function (kept for compatibility)
function scrollToSection(sectionId) {
    const section = document.getElementById(sectionId);
    if (section) {
        section.scrollIntoView({ behavior: 'smooth', block: 'start' });
        // Expand the section if it's collapsed
        const content = document.getElementById(sectionId + 'Content');
        const icon = document.getElementById(sectionId + 'Icon');
        if (content && icon && !content.classList.contains('expanded')) {
            content.classList.add('expanded');
            icon.classList.add('expanded');
        }
    }
}

// Host Tools Functions
function openHostToolsPanel() {
    vscode.postMessage({
        command: 'openHostToolsPanel'
    });
}

function markToolsComplete() {
    vscode.postMessage({
        command: 'markToolsComplete'
    });
}

// Command Functions
function openWingetInstall() {
    vscode.postMessage({
        command: 'openWingetLink'
    });
}

function openFolder() {
    vscode.postMessage({
        command: 'openFolder'
    });
}

function reinitializeWorkspace() {
    vscode.postMessage({
        command: 'reinitializeWorkspace'
    });
}

function installSDK() {
    vscode.postMessage({
        command: 'installSDK'
    });
}

function setupWestEnvironment() {
    vscode.postMessage({
        command: 'setupWestEnvironment'
    });
}

function westInit() {
    vscode.postMessage({
        command: 'westInit'
    });
}

function westUpdate() {
    vscode.postMessage({
        command: 'westUpdate'
    });
}

function manageWorkspace() {
    vscode.postMessage({
        command: 'manageWorkspace'
    });
}

function selectExistingWestWorkspace() {
    setWorkspaceState('initializing');
    vscode.postMessage({
        command: 'selectExistingWestWorkspace'
    });
}

// SDK Management Functions
function listSDKs() {
    // Show loading state in the sdkListContainer
    const containerDiv = document.getElementById('sdkListContainer');

    if (containerDiv) {
        containerDiv.innerHTML = '<div style="display: flex; align-items: center; gap: 8px; padding: 10px;"><div class="loading-spinner"></div><span>Loading SDK information...</span></div>';
    }

    vscode.postMessage({
        command: 'listSDKs'
    });
}

function displaySDKList(sdkData) {
    const containerDiv = document.getElementById('sdkListContainer');

    if (!containerDiv) {
        return;
    }

    if (!sdkData.success) {
        containerDiv.innerHTML = `
            <div style="padding: 15px; border: 1px solid var(--vscode-inputValidation-errorBorder); border-radius: 6px; background-color: var(--vscode-inputValidation-errorBackground); color: var(--vscode-inputValidation-errorForeground);">
                <strong>Error:</strong> ${escapeHtml(sdkData.error || 'Failed to list SDKs')}
            </div>
        `;
        return;
    }

    if (!sdkData.versions || sdkData.versions.length === 0) {
        containerDiv.innerHTML = `
            <div style="padding: 15px; border: 1px solid var(--vscode-panel-border); border-radius: 6px; background-color: var(--vscode-editor-background); color: var(--vscode-descriptionForeground); text-align: center;">
                No SDK versions found. Try installing an SDK first.
            </div>
        `;
        return;
    }

    let html = '';
    for (const version of sdkData.versions) {
        // Escape all user-provided data to prevent XSS
        const escapedVersion = escapeHtml(version.version || '');
        const escapedPath = escapeHtml(version.path || '');

        html += `
            <div class="sdk-version-card">
                <div class="sdk-version-header">
                    <div class="sdk-version-title">Zephyr SDK ${escapedVersion}</div>
                </div>
                <div class="sdk-path">${escapedPath}</div>
                
                ${version.installedToolchains && version.installedToolchains.length > 0 ? `
                    <div class="toolchain-section">
                        <div class="toolchain-section-title">Installed Toolchains (${version.installedToolchains.length}):</div>
                        <div class="toolchain-list">
                            ${version.installedToolchains.map(tc => `<span class="toolchain-tag">${escapeHtml(tc)}</span>`).join('')}
                        </div>
                    </div>
                ` : ''}
                
                ${version.availableToolchains && version.availableToolchains.length > 0 ? `
                    <div class="toolchain-section">
                        <div class="toolchain-section-title">Available Toolchains (${version.availableToolchains.length}):</div>
                        <div class="toolchain-list">
                            ${version.availableToolchains.map(tc => `<span class="toolchain-tag available">${escapeHtml(tc)}</span>`).join('')}
                        </div>
                    </div>
                ` : ''}
            </div>
        `;
    }

    containerDiv.innerHTML = html;
}

// Workspace Setup Functions - Now direct handlers

/**
 * Set the workspace sub-page to one of its three mutually exclusive states:
 *   "initializing"    — a setup operation is running
 *   "ready"           — workspace is configured
 *   "setup-required"  — no workspace configured
 *
 * CSS rules on [data-workspace-state] hide/show the matching .ws-state-*
 * container, so no DOM surgery is needed — just flip the attribute.
 */
function setWorkspaceState(state) {
    var body = document.querySelector('.sub-page-body[data-workspace-state]');
    if (body) {
        body.setAttribute('data-workspace-state', state);
    }
}

/**
 * Update the workspace card on the overview page to reflect setup status.
 * @param {'initializing' | 'ready' | 'failed'} state
 */
function updateWorkspaceCardStatus(state) {
    var el = document.getElementById('workspaceCardStatus');
    if (!el) {
        return;
    }
    // Remove all status-* classes, then set the new one.
    el.className = 'status';
    switch (state) {
        case 'initializing':
            el.classList.add('status-info');
            el.innerHTML = '<div class="loading-spinner"></div> Initializing\u2026';
            break;
        case 'ready':
            el.classList.add('status-success');
            el.textContent = '\u2713 Initialized';
            break;
        case 'failed':
            el.classList.add('status-error');
            el.textContent = '\u2717 Setup Failed';
            break;
    }
}

/**
 * Switch to the initializing state.
 * Called immediately when any setup button is clicked so the user sees
 * instant feedback instead of the page appearing to hang.
 *
 * Only flips the state attribute if the workspace page is already rendered.
 * Does NOT force-navigate — the user is already on the workspace page when
 * clicking a setup button.
 */
function showWorkspaceInitializing() {
    // Mark setup as active so that if the user later navigates to the workspace
    // page, showSubPage will switch it to the initializing state.
    _workspaceSetupActive = true;

    var body = document.querySelector('.sub-page-body[data-workspace-state]');
    if (body) {
        // Container already rendered — just flip the state.
        body.setAttribute('data-workspace-state', 'initializing');
    }
    // If the workspace page isn't rendered, do nothing here.
    // showSubPage will check _workspaceSetupActive when the user navigates.

    // Update the overview card to reflect the initializing state.
    updateWorkspaceCardStatus('initializing');
}

function workspaceSetupFromGit() {
    showWorkspaceInitializing();
    vscode.postMessage({
        command: 'workspaceSetupFromGit'
    });
}

function workspaceSetupFromWestGit() {
    showWorkspaceInitializing();
    vscode.postMessage({
        command: 'workspaceSetupFromWestGit'
    });
}

function workspaceSetupStandard() {
    showWorkspaceInitializing();
    vscode.postMessage({
        command: 'workspaceSetupStandard'
    });
}

function workspaceSetupFromCurrentDirectory() {
    showWorkspaceInitializing();
    vscode.postMessage({
        command: 'workspaceSetupFromCurrentDirectory'
    });
}

function workspaceSetupPicker() {
    vscode.postMessage({
        command: 'workspaceSetupPicker'
    });
}

/**
 * Opens the West configuration panel to detect existing west configurations
 * or create new west.yml files from templates
 */
function westConfig() {
    vscode.postMessage({
        command: 'westConfig'
    });
}

// West.yml editor functions
function openWestYml() {
    vscode.postMessage({
        command: 'openWestYml'
    });
}

function saveAndUpdateWestYml() {
    const editor = document.getElementById('westYmlEditor');
    if (editor) {
        const content = editor.value;
        vscode.postMessage({
            command: 'saveAndUpdateWestYml',
            content: content
        });
    }
}

function loadWestYmlContent(content) {
    const editor = document.getElementById('westYmlEditor');
    if (editor) {
        editor.value = content || '';

        // Add tab key handler if not already added
        if (!editor.dataset.tabHandlerAdded) {
            editor.addEventListener('keydown', function (e) {
                if (e.key === 'Tab') {
                    e.preventDefault();

                    // Get cursor position
                    const start = this.selectionStart;
                    const end = this.selectionEnd;

                    // Insert two spaces at cursor position
                    const value = this.value;
                    this.value = value.substring(0, start) + '  ' + value.substring(end);

                    // Move cursor after the inserted spaces
                    this.selectionStart = this.selectionEnd = start + 2;
                }
            });
            editor.dataset.tabHandlerAdded = 'true';
        }
    }
}

// Copy to clipboard function from data attribute
function copyToClipboardFromData(element) {
    const text = element.getAttribute('data-command');
    if (!text) {
        console.error('No command data found');
        return;
    }
    copyToClipboard(text, element);
}

// Copy to clipboard function
function copyToClipboard(text, element) {
    // Function to handle feedback
    function showFeedback(success = true) {
        const indicator = element.nextElementSibling;
        if (!indicator || !indicator.classList.contains('copy-indicator')) {
            return;
        }

        const originalText = indicator.textContent;
        const originalColor = indicator.style.color;

        if (success) {
            indicator.textContent = 'Copied!';
            indicator.style.color = 'var(--vscode-terminal-ansiGreen)';
        } else {
            indicator.textContent = 'Failed to copy';
            indicator.style.color = 'var(--vscode-terminal-ansiRed)';
        }

        setTimeout(() => {
            indicator.textContent = originalText;
            indicator.style.color = originalColor;
        }, 2000);
    }

    // Try modern clipboard API first
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(() => {
            showFeedback(true);
        }).catch(err => {
            console.error('Clipboard API failed:', err);
            // Try fallback
            tryFallback();
        });
    } else {
        // Use fallback directly
        tryFallback();
    }

    function tryFallback() {
        try {
            const textArea = document.createElement('textarea');
            textArea.value = text;
            textArea.style.position = 'fixed';
            textArea.style.left = '-999999px';
            textArea.style.top = '-999999px';
            document.body.appendChild(textArea);
            textArea.focus();
            textArea.select();

            const successful = document.execCommand('copy');
            document.body.removeChild(textArea);

            showFeedback(successful);
            if (!successful) {
                console.error('Fallback copy failed');
            }
        } catch (err) {
            console.error('Fallback copy failed:', err);
            showFeedback(false);
        }
    }
}

// Host Tools Manager Functions
function refreshHostToolsStatus() {
    vscode.postMessage({
        command: 'checkHostToolsStatus'
    });
}

function installAllMissingTools() {
    vscode.postMessage({
        command: 'installAllMissingTools'
    });
}

function installSinglePackage(packageName) {
    vscode.postMessage({
        command: 'installPackage',
        packageName: packageName
    });
}

function installPackageManagerTool() {
    vscode.postMessage({
        command: 'installPackageManager'
    });
}

function updateHostToolsStatus(data, error) {
    const managerStatus = document.getElementById('manager-status');
    const packagesStatus = document.getElementById('packages-status');
    const installAllBtn = document.getElementById('install-all-btn');

    if (!managerStatus || !packagesStatus) {
        return;
    }

    if (error) {
        managerStatus.innerHTML = `<div class="error">Error: ${escapeHtml(error)}</div>`;
        packagesStatus.innerHTML = `<div class="error">Unable to check package status</div>`;
        return;
    }

    // Update package manager status
    if (!data.managerAvailable) {
        managerStatus.innerHTML = `
            <div class="warning">
                <strong>${escapeHtml(data.managerName)}</strong> is not installed or not in PATH.
                <div style="margin-top: 10px;">
                    <button class="button button-secondary" onclick="installPackageManagerTool()">
                        Install ${escapeHtml(data.managerName)}
                    </button>
                </div>
            </div>
        `;
    } else {
        managerStatus.innerHTML = `
            <div class="success">
                ✓ <strong>${escapeHtml(data.managerName)}</strong> is available
            </div>
        `;
    }

    // Update packages status
    if (!data.packages || data.packages.length === 0) {
        packagesStatus.innerHTML = '<div class="info">No packages to check</div>';
        return;
    }

    let html = '<table class="packages-table">';
    html += '<thead><tr><th>Package</th><th>Status</th><th>Action</th></tr></thead><tbody>';

    let actuallyMissing = false;
    for (const pkg of data.packages) {
        // Check if this package has a saved pending-restart state
        const savedState = hostToolsInstallationState.packageStates[pkg.name];
        const isPendingRestart = savedState === 'pending-restart';
        const isInstalling = savedState === 'installing';

        // Determine the actual state to display
        let statusClass, statusText, showInstallButton;

        if (isInstalling) {
            statusClass = 'info';
            statusText = '<span class="codicon codicon-sync codicon-modifier-spin"></span> Installing';
            showInstallButton = false;
        } else if (isPendingRestart) {
            statusClass = 'warning';
            statusText = '<span class="codicon codicon-warning"></span> Not Available Pending Restart';
            showInstallButton = false;
        } else if (pkg.available) {
            statusClass = 'success';
            statusText = '✓ Installed';
            showInstallButton = false;
        } else {
            statusClass = 'error';
            statusText = '✗ Not Available';
            showInstallButton = true;
            actuallyMissing = true;
        }

        html += `<tr>
            <td><strong>${escapeHtml(pkg.name)}</strong></td>
            <td><span class="${statusClass}">${statusText}</span></td>
            <td>`;

        if (showInstallButton) {
            html += `<button class="button button-small" onclick="installSinglePackage('${escapeHtml(pkg.name)}')">Install</button>`;
        }

        html += `</td></tr>`;
    }

    html += '</tbody></table>';
    packagesStatus.innerHTML = html;

    // Enable/disable install all button - disable if installation in progress or no packages to install
    if (installAllBtn) {
        installAllBtn.disabled = !actuallyMissing || !data.managerAvailable || hostToolsInstallationState.inProgress;
    }
}

function handleHostToolsStartInstallAll() {
    // Get current status and filter packages
    const packagesStatus = document.getElementById('packages-status');
    if (!packagesStatus) {
        return;
    }

    const table = packagesStatus.querySelector('.packages-table');
    if (!table) {
        return;
    }

    const packagesToInstall = [];
    const rows = table.querySelectorAll('tbody tr');

    for (const row of rows) {
        const nameCell = row.querySelector('td:first-child strong');
        if (!nameCell) {
            continue;
        }

        const packageName = nameCell.textContent.trim();
        const savedState = hostToolsInstallationState.packageStates[packageName];
        const isPendingRestart = savedState === 'pending-restart';
        const isInstalling = savedState === 'installing';

        // Only install if there's an install button (meaning not available and not pending restart)
        const installButton = row.querySelector('.button');
        if (installButton && !isPendingRestart && !isInstalling) {
            packagesToInstall.push(packageName);
        }
    }

    // Send the filtered list back to the extension
    vscode.postMessage({
        command: 'installAllMissingToolsPackages',
        packageNames: packagesToInstall
    });
}

function handleHostToolsInstallAllStarted(total) {
    hostToolsInstallationState.inProgress = true;
    const installAllBtn = document.getElementById('install-all-btn');
    if (installAllBtn) {
        installAllBtn.disabled = true;
        installAllBtn.innerHTML = `
            <span class="codicon codicon-sync codicon-modifier-spin"></span>
            Installing Packages (0/${total})
        `;
    }
}

function handleHostToolsPackageInstalling(packageName, current, total) {
    // Update the button text only if installing multiple packages
    if (total > 1) {
        const installAllBtn = document.getElementById('install-all-btn');
        if (installAllBtn) {
            // Ensure values are numbers to prevent XSS
            const currentNum = Number(current);
            const totalNum = Number(total);
            installAllBtn.innerHTML = `
                <span class="codicon codicon-sync codicon-modifier-spin"></span>
                Installing Packages (${currentNum}/${totalNum})
            `;
        }
    }

    // Save the state and update the specific package row in the table
    hostToolsInstallationState.packageStates[packageName] = 'installing';
    updateHostToolsPackageStatus(packageName, 'installing');
}

function handleHostToolsPackageInstalled(packageName, success, pendingRestart, current, total) {
    // Update and save package state
    let state = 'error';
    if (success && !pendingRestart) {
        state = 'installed';
    } else if (success && pendingRestart) {
        state = 'pending-restart';
    }

    hostToolsInstallationState.packageStates[packageName] = state;
    updateHostToolsPackageStatus(packageName, state);
}

function handleHostToolsInstallAllComplete(needsRestart, hasErrors) {
    hostToolsInstallationState.inProgress = false;
    const installAllBtn = document.getElementById('install-all-btn');
    if (installAllBtn) {
        if (needsRestart) {
            installAllBtn.innerHTML = `
                <span class="codicon codicon-warning"></span>
                Pending Restart
            `;
        } else if (hasErrors) {
            installAllBtn.innerHTML = `
                <span class="codicon codicon-error"></span>
                Installation Failed
            `;
        } else {
            installAllBtn.innerHTML = `
                <span class="codicon codicon-check"></span>
                All Packages Installed
            `;
        }

        // Re-enable button after a delay
        setTimeout(() => {
            installAllBtn.disabled = false;
            refreshHostToolsStatus();
        }, 2000);
    }
}

function updateHostToolsPackageStatus(packageName, state) {
    const packagesTable = document.querySelector('.packages-table');
    if (!packagesTable) {
        return;
    }

    const rows = packagesTable.querySelectorAll('tbody tr');
    for (const row of rows) {
        const nameCell = row.querySelector('td:first-child strong');
        if (nameCell && nameCell.textContent.trim() === packageName) {
            const statusCell = row.querySelector('td:nth-child(2)');
            const actionCell = row.querySelector('td:nth-child(3)');

            if (!statusCell) {
                continue;
            }

            // Update status text and style
            switch (state) {
                case 'installing':
                    statusCell.innerHTML = '<span class="info"><span class="codicon codicon-sync codicon-modifier-spin"></span> Installing</span>';
                    if (actionCell) {
                        actionCell.innerHTML = '';
                    }
                    break;
                case 'installed':
                    statusCell.innerHTML = '<span class="success">✓ Installed</span>';
                    if (actionCell) {
                        actionCell.innerHTML = '';
                    }
                    break;
                case 'pending-restart':
                    statusCell.innerHTML = '<span class="warning"><span class="codicon codicon-warning"></span> Not Available Pending Restart</span>';
                    if (actionCell) {
                        actionCell.innerHTML = '';
                    }
                    break;
                case 'error':
                    statusCell.innerHTML = '<span class="error">✗ Installation Failed</span>';
                    break;
            }
            break;
        }
    }
}

// Workspace Setup Progress Functions

/**
 * Handles workspace setup progress events by rendering a progress panel
 * at the top of the workspace setup sub-page. If the workspace sub-page
 * is not currently visible, the progress panel navigates to it first.
 * @param {object} data - The progress event data
 * @param {string} data.type - Event type: 'start', 'step-update', 'complete', or 'failed'
 * @param {string} data.operationLabel - Label for the operation
 * @param {Array} data.steps - Step objects: { id, label, status, detail? }
 * @param {string} [data.message] - Optional message
 */
function handleWorkspaceSetupProgress(data) {
    // A 'start' or 'step-update' event while not yet tracking means a setup
    // operation is in progress (e.g. panel opened mid-setup). Activate tracking.
    if (data.type === 'start' || data.type === 'step-update') {
        _workspaceSetupActive = true;
        updateWorkspaceCardStatus('initializing');
    }

    // On complete or failure, mark setup as no longer active.
    if (data.type === 'complete' || data.type === 'failed') {
        _workspaceSetupActive = false;
        updateWorkspaceCardStatus(data.type === 'complete' ? 'ready' : 'failed');
    }

    // Don't render progress panel unless relevant.
    if (!_workspaceSetupActive && data.type !== 'complete' && data.type !== 'failed') {
        return;
    }

    // Only update the workspace sub-page progress panel if it is already visible.
    // Never force-navigate — the user may be on the overview or another page.
    var subPageContainer = document.getElementById('subPageContainer');
    if (!subPageContainer || !subPageContainer.classList.contains('visible')) {
        // Workspace page not visible. State will be applied when the user
        // navigates to it (showSubPage checks _workspaceSetupActive).
        return;
    }

    // Ensure the initializing state is active.
    setWorkspaceState('initializing');

    // The progress container is pre-rendered inside .ws-state-initializing.
    var container = document.getElementById('setupProgressContainer');
    if (!container) {
        return;
    }

    // Clear any pending dismiss timer
    if (_setupProgressDismissTimer) {
        clearTimeout(_setupProgressDismissTimer);
        _setupProgressDismissTimer = null;
    }

    if (data.type === 'complete') {
        _setupProgressDismissTimer = setTimeout(function () {
            dismissSetupProgress();
        }, 8000);
    }

    // Determine header style based on event type
    let bannerClass, bannerIcon, bannerText;
    switch (data.type) {
        case 'complete':
            bannerClass = 'status-success';
            bannerIcon = '<span class="codicon codicon-check"></span>';
            bannerText = 'Setup Complete';
            break;
        case 'failed':
            bannerClass = 'status-error';
            bannerIcon = '<span class="codicon codicon-error"></span>';
            bannerText = 'Setup Failed';
            break;
        default:
            bannerClass = 'status-info';
            bannerIcon = '';
            bannerText = 'Setting Up Workspace...';
            break;
    }

    function getStepIcon(status) {
        switch (status) {
            case 'completed':
                return '<span class="setup-step-icon completed"><span class="codicon codicon-check"></span></span>';
            case 'in-progress':
                return '<span class="setup-step-icon in-progress"><span class="codicon codicon-sync codicon-modifier-spin"></span></span>';
            case 'failed':
                return '<span class="setup-step-icon failed"><span class="codicon codicon-error"></span></span>';
            case 'skipped':
                return '<span class="setup-step-icon skipped"><span class="codicon codicon-dash"></span></span>';
            default:
                return '<span class="setup-step-icon pending"><span class="codicon codicon-circle-outline"></span></span>';
        }
    }

    const stepsHtml = data.steps.map(function (step) {
        const detail = step.detail
            ? '<span class="setup-step-detail">' + escapeHtml(step.detail) + '</span>'
            : '';
        return '' +
            '<div class="setup-step-item ' + step.status + '">' +
            getStepIcon(step.status) +
            '<div class="setup-step-content">' +
            '<span class="setup-step-label">' + escapeHtml(step.label) + '</span>' +
            detail +
            '</div>' +
            '</div>';
    }).join('');

    const bannerSpinner = (data.type === 'start' || data.type === 'step-update')
        ? '<div class="loading-spinner"></div>'
        : '';

    const messageHtml = data.message
        ? '<p class="setup-progress-message">' + escapeHtml(data.message) + '</p>'
        : '';

    // Show a dismiss button when complete or failed
    const dismissBtn = (data.type === 'complete' || data.type === 'failed')
        ? '<button class="setup-progress-dismiss" onclick="dismissSetupProgress()" title="Dismiss">' +
        '<span class="codicon codicon-close"></span>' +
        '</button>'
        : '';

    const html = '' +
        '<div class="setup-progress-panel">' +
        '<div class="setup-progress-header ' + bannerClass + '">' +
        bannerSpinner +
        '<span class="status-icon">' + bannerIcon + '</span>' +
        '<span class="setup-progress-title">' + escapeHtml(data.operationLabel) + ' — ' + bannerText + '</span>' +
        dismissBtn +
        '</div>' +
        '<div class="setup-progress-body">' +
        '<div class="setup-progress-steps">' +
        stepsHtml +
        '</div>' +
        messageHtml +
        '</div>' +
        '</div>';

    container.innerHTML = html;
}

/** Dismiss / hide the progress panel content. */
function dismissSetupProgress() {
    var container = document.getElementById('setupProgressContainer');
    if (container) {
        // Clear content but keep the container in the DOM (it's part of the
        // pre-rendered initializing state and may be reused).
        container.innerHTML = '';
    }
    if (_setupProgressDismissTimer) {
        clearTimeout(_setupProgressDismissTimer);
        _setupProgressDismissTimer = null;
    }
}
// Message Listener for SDK list (handled by main listener above)
// Removed duplicate sdkListResult handler to prevent displaySDKList firing twice
