/*
Copyright 2026 mylonics 
Author Rijesh Augustine

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * Parser for Zephyr's `<build>/zephyr/runners.yaml`. This file is generated by
 * the Zephyr build system and contains the canonical information needed to
 * flash and debug a build: ELF/HEX file names, GDB executable, the list of
 * available runners, the default debug/flash runner, and per-runner argument
 * lists.
 *
 * We use this as the source of truth for synthesizing cortex-debug debug
 * configurations on the fly so users no longer need to hand-maintain a
 * launch.json with cortex-debug specifics.
 */

import * as fs from "fs";
import * as path from "upath";
import * as yaml from "js-yaml";

import { outputWarning } from "../utilities/output";
import { WEST_DEBUG_RUNNERS } from "../project_utilities/runner_selector";

/**
 * Parsed contents of runners.yaml. All fields are best-effort — the file may
 * be absent or partially populated depending on how far the build progressed.
 */
export interface RunnersYaml {
  /** Build directory recorded in the file (config.build_dir). */
  buildDir?: string;
  /** Board directory (config.board_dir). Useful for locating SVDs. */
  boardDir?: string;
  /** Absolute path to the ELF file (config.elf_file resolved against build dir). */
  elfFile?: string;
  /** Absolute path to the HEX file (config.hex_file resolved against build dir). */
  hexFile?: string;
  /** Absolute path to the BIN file (config.bin_file resolved against build dir). */
  binFile?: string;
  /** Absolute path to the GDB executable (config.gdb). */
  gdb?: string;
  /** Absolute path to OpenOCD if recorded (config.openocd). */
  openocd?: string;
  /** Optional OpenOCD search directories (config.openocd_search). */
  openocdSearch?: string[];
  /** All known runners (top-level `runners`). */
  runners: string[];
  /** The default flash runner (`flash-runner`). */
  flashRunner?: string;
  /** The default debug runner (`debug-runner`). */
  debugRunner?: string;
  /** Per-runner argument arrays (`args`). */
  args: { [runner: string]: string[] };
}

/** A single sysbuild domain as described in domains.yaml. */
export interface SysbuildDomain {
  name: string;
  buildDir: string;
}

/**
 * Read the sysbuild `domains.yaml` in a top-level build directory and return
 * the list of image domains. Returns undefined when `domains.yaml` does not
 * exist (i.e. the project is not using sysbuild).
 */
export function getSysbuildDomains(buildDir: string): SysbuildDomain[] | undefined {
  const domainsYamlPath = path.join(buildDir, "domains.yaml");
  if (!fs.existsSync(domainsYamlPath)) {
    return undefined;
  }
  try {
    const doc: any = yaml.load(fs.readFileSync(domainsYamlPath, "utf-8"));
    const domains: any[] = doc?.domains;
    if (Array.isArray(domains)) {
      return domains
        .filter((d: any) => typeof d?.name === "string" && typeof d?.build_dir === "string")
        .map((d: any) => ({ name: d.name as string, buildDir: d.build_dir as string }));
    }
  } catch (e) {
    // Malformed domains.yaml — log so the caller's "No sysbuild domains
    // found" message has a breadcrumb in the output channel.
    outputWarning("Runners YAML", `Failed to parse ${domainsYamlPath}: ${String(e)}`);
  }
  return undefined;
}

/**
 * Resolve the path to runners.yaml for a build directory. Handles sysbuild by
 * delegating to the named domain (or default domain when omitted) via domains.yaml.
 *
 * Returns the absolute path even if the file does not exist; callers should
 * check existence themselves so they can produce a useful error.
 */
export function resolveRunnersYamlPath(buildDir: string, domainName?: string): string {
  const domainsYamlPath = path.join(buildDir, "domains.yaml");
  let effectiveBuildDir = buildDir;
  if (fs.existsSync(domainsYamlPath)) {
    try {
      const domainsDoc: any = yaml.load(fs.readFileSync(domainsYamlPath, "utf-8"));
      const targetName = domainName ?? domainsDoc?.default;
      const domains: any[] = domainsDoc?.domains;
      if (targetName && Array.isArray(domains)) {
        const targetDomain = domains.find((d: any) => d?.name === targetName);
        if (targetDomain?.build_dir) {
          effectiveBuildDir = targetDomain.build_dir;
        }
      }
    } catch (e) {
      // Fall through with the original build dir, but log so debug sessions
      // that suddenly resolve to the wrong runners.yaml have a breadcrumb.
      outputWarning("Runners YAML", `Failed to parse ${domainsYamlPath}: ${String(e)}`);
    }
  }
  return path.join(effectiveBuildDir, "zephyr", "runners.yaml");
}

/**
 * In-memory cache for parsed runners.yaml files, keyed by absolute path.
 *
 * Validity is checked against the on-disk file's `mtimeMs` and `size`: if
 * either changes (e.g. the build system regenerated runners.yaml), the cache
 * entry is discarded and the file is re-parsed. A pristine build deletes the
 * build folder entirely, so the next stat() will either fail (entry dropped)
 * or report a fresh mtime (entry refreshed). For belt-and-suspenders against
 * filesystems with coarse mtime resolution, callers can also explicitly drop
 * entries via {@link invalidateRunnersYamlCache}.
 *
 * The cached object is frozen so accidental mutation by a caller cannot
 * corrupt the entry for the next caller.
 */
interface RunnersYamlCacheEntry {
  mtimeMs: number;
  size: number;
  parsed: RunnersYaml;
}
const runnersYamlCache = new Map<string, RunnersYamlCacheEntry>();

/**
 * Drop cached runners.yaml entries. Pass a build directory to invalidate only
 * entries underneath it (e.g. on pristine build); pass nothing to clear the
 * entire cache (e.g. on workspace reload).
 */
export function invalidateRunnersYamlCache(buildDir?: string): void {
  if (!buildDir) {
    runnersYamlCache.clear();
    return;
  }
  const prefix = path.normalize(buildDir);
  for (const key of runnersYamlCache.keys()) {
    if (path.normalize(key).startsWith(prefix)) {
      runnersYamlCache.delete(key);
    }
  }
}

/**
 * Parse a runners.yaml file. Returns undefined when the file does not exist or
 * cannot be parsed. Relative file paths inside `config.*_file` are resolved
 * against `config.build_dir/zephyr` to produce absolute paths.
 *
 * Results are cached in-process keyed by path, with `mtimeMs`+`size` used as
 * the validity check so a regenerated runners.yaml is picked up automatically
 * on the next call. The hot path is a single `fs.statSync` (no YAML re-parse,
 * no file read) which keeps repeated debug-config resolution and UI refreshes
 * cheap.
 */
export function parseRunnersYaml(runnersYamlPath: string): RunnersYaml | undefined {
  let stat: fs.Stats;
  try {
    stat = fs.statSync(runnersYamlPath);
  } catch {
    // File missing (or otherwise unreadable) — drop any stale cache entry so
    // a subsequent post-build read parses fresh content.
    runnersYamlCache.delete(runnersYamlPath);
    return undefined;
  }
  const cached = runnersYamlCache.get(runnersYamlPath);
  if (cached && cached.mtimeMs === stat.mtimeMs && cached.size === stat.size) {
    return cached.parsed;
  }
  let doc: any;
  try {
    doc = yaml.load(fs.readFileSync(runnersYamlPath, "utf-8"));
  } catch (e) {
    outputWarning("Runners YAML", `Failed to parse ${runnersYamlPath}: ${String(e)}`);
    runnersYamlCache.delete(runnersYamlPath);
    return undefined;
  }
  if (!doc || typeof doc !== "object") {
    runnersYamlCache.delete(runnersYamlPath);
    return undefined;
  }

  const config = (doc.config && typeof doc.config === "object") ? doc.config : {};
  const buildDir: string | undefined = typeof config.build_dir === "string" ? config.build_dir : undefined;
  const zephyrDir = buildDir ? path.join(buildDir, "zephyr") : path.dirname(runnersYamlPath);

  const resolveFile = (val: any): string | undefined => {
    if (typeof val !== "string" || !val) { return undefined; }
    return path.isAbsolute(val) ? val : path.join(zephyrDir, val);
  };

  const argsObj: { [runner: string]: string[] } = {};
  if (doc.args && typeof doc.args === "object") {
    for (const [runnerName, value] of Object.entries(doc.args)) {
      if (Array.isArray(value)) {
        argsObj[runnerName] = value.filter((v): v is string => typeof v === "string");
      }
    }
  }

  const runners: string[] = Array.isArray(doc.runners)
    ? doc.runners.filter((r: any): r is string => typeof r === "string")
    : [];

  const parsed: RunnersYaml = Object.freeze({
    buildDir,
    boardDir: typeof config.board_dir === "string" ? config.board_dir : undefined,
    elfFile: resolveFile(config.elf_file),
    hexFile: resolveFile(config.hex_file),
    binFile: resolveFile(config.bin_file),
    gdb: typeof config.gdb === "string" ? config.gdb : undefined,
    openocd: typeof config.openocd === "string" ? config.openocd : undefined,
    openocdSearch: Array.isArray(config.openocd_search)
      ? config.openocd_search.filter((s: any): s is string => typeof s === "string")
      : undefined,
    runners,
    flashRunner: typeof doc["flash-runner"] === "string" ? doc["flash-runner"] : undefined,
    debugRunner: typeof doc["debug-runner"] === "string" ? doc["debug-runner"] : undefined,
    args: argsObj,
  });

  runnersYamlCache.set(runnersYamlPath, {
    mtimeMs: stat.mtimeMs,
    size: stat.size,
    parsed,
  });
  return parsed;
}

/**
 * Look for an SVD file in the board directory recorded in runners.yaml.
 * Returns the absolute path to the best matching `.svd` file, or undefined.
 *
 * Zephyr boards occasionally ship an `.svd` file beside the board YAML; this
 * is a best-effort lookup so the cortex-debug peripheral viewer can be
 * populated automatically when one is present.
 *
 * When `hint` is provided (typically the board or SoC name), the lookup
 * prefers a `.svd` whose basename contains the hint (case-insensitive). This
 * disambiguates board directories that ship multiple SoC SVDs (issue #20).
 */
/**
 * In-memory cache for {@link findSvdFile}. Board directories change very
 * rarely (only when the user edits the Zephyr tree or switches modules), so
 * caching the directory listing per (boardDir, hint) avoids a `readdirSync`
 * on every debug session. Invalidated by the board directory's `mtimeMs`,
 * which Zephyr's build system bumps when files are added/removed.
 */
interface SvdCacheEntry {
  mtimeMs: number;
  result: string | undefined;
}
const svdCache = new Map<string, SvdCacheEntry>();

export function findSvdFile(boardDir: string | undefined, hint?: string): string | undefined {
  if (!boardDir) { return undefined; }
  let stat: fs.Stats;
  try {
    stat = fs.statSync(boardDir);
  } catch {
    return undefined;
  }
  const cacheKey = `${boardDir}|${hint ?? ""}`;
  const cached = svdCache.get(cacheKey);
  if (cached && cached.mtimeMs === stat.mtimeMs) {
    return cached.result;
  }
  let result: string | undefined;
  try {
    const entries = fs.readdirSync(boardDir).filter(e => e.toLowerCase().endsWith(".svd"));
    if (entries.length === 0) {
      result = undefined;
    } else if (hint) {
      const needle = hint.toLowerCase();
      const match = entries.find(e => e.toLowerCase().includes(needle));
      result = path.join(boardDir, match ?? entries[0]);
    } else {
      result = path.join(boardDir, entries[0]);
    }
  } catch {
    result = undefined;
  }
  svdCache.set(cacheKey, { mtimeMs: stat.mtimeMs, result });
  return result;
}

/**
 * Stlink runner variants in priority order (highest preference first).
 * All three expose the ST-LINK GDB server and map to cortex-debug servertype `"stlink"`.
 * The user-facing canonical name is `"stlink"`; use {@link resolveCanonicalRunner}
 * to pick the right variant when consulting a build's runners.yaml.
 */
const STLINK_VARIANTS = ["stlink", "stlink_gdbserver", "stm32cubeprogrammer-stlink"] as const;

/** BMP runner variants in priority order. The canonical user-facing name is `"bmp"`. */
const BMP_VARIANTS = ["blackmagicprobe", "bmp"] as const;

/**
 * Resolve a canonical user-facing runner name to the actual Zephyr runner name
 * present in a build's runner list.
 *
 * - **stlink family**: `"stlink"` → first of `[stlink, stlink_gdbserver, stm32cubeprogrammer-stlink]` found.
 * - **bmp family**: `"bmp"` → first of `[blackmagicprobe, bmp]` found.
 * - All other names pass through unchanged.
 */
export function resolveCanonicalRunner(runner: string, available: string[]): string {
  if (runner === "stlink") {
    for (const variant of STLINK_VARIANTS) {
      if (available.includes(variant)) { return variant; }
    }
  } else if (runner === "bmp") {
    for (const variant of BMP_VARIANTS) {
      if (available.includes(variant)) { return variant; }
    }
  }
  return runner;
}

/**
 * Translate a Zephyr runner name to a cortex-debug `servertype`. Returns
 * undefined when the runner cannot be driven by cortex-debug at all.
 *
 * Mappings fall into three groups:
 *
 * 1. **Native servertypes** — cortex-debug ships a built-in server for the
 *    runner (jlink, openocd, pyocd, stlink, bmp, qemu).
 * 2. **External bridge** — runner has no native cortex-debug servertype but
 *    speaks the GDB remote protocol when launched via `west debugserver`.
 *    Returns `"external"`; callers check {@link runnerNeedsBridge} and then
 *    spawn the server before connecting. See {@link WEST_DEBUG_RUNNERS} for
 *    the full list.
 * 3. **Unsupported** — flash-only runners (dfu-util, uf2, bossac, …)
 *    return `undefined`; the debug provider surfaces an actionable error.
 *
 * Notes on specific runners:
 * - `stlink`, `stlink_gdbserver`, and `stm32cubeprogrammer-stlink` all map to
 *   the `"stlink"` servertype. The canonical user-facing name is `"stlink"`;
 *   use {@link resolveCanonicalRunner} to pick the right variant at debug time.
 * - `stm32cubeprogrammer` (no `-stlink` suffix) is bridged via `west debugserver`.
 * - `qemu` is mapped to cortex-debug's `"qemu"` servertype.
 */
export function runnerToServerType(runner: string): string | undefined {
  switch (runner) {
    case "jlink":
      return "jlink";
    case "openocd":
      return "openocd";
    case "pyocd":
      return "pyocd";
    case "stlink":
    case "stlink_gdbserver":
    case "stm32cubeprogrammer-stlink":
      return "stlink";
    case "blackmagicprobe":
    case "bmp":
      return "bmp";
    case "qemu":
      return "qemu";
    default:
      if (WEST_DEBUG_RUNNERS.includes(runner)) { return "external"; }
      return undefined;
  }
}

/**
 * True when {@link runnerToServerType} maps `runner` to cortex-debug's
 * `"external"` servertype via the `west debugserver` bridge. Callers that
 * synthesize cortex-debug configurations must spawn the bridge server and
 * inject the resulting `gdbTarget` before handing the config to cortex-debug.
 */
export function runnerNeedsBridge(runner: string): boolean {
  return WEST_DEBUG_RUNNERS.includes(runner);
}

/**
 * Read the `runners.yaml` in a build folder and return a lightweight hint
 * object for display in the UI. Returns undefined when the file does not exist
 * (i.e., the build has not been run yet).
 */
export function getRunnersYamlHint(buildFolder: string, sysbuildImage?: string): {
  flashRunner?: string;
  debugRunner?: string;
  availableRunners: string[];
  /** Absolute path to the runners.yaml file that was parsed. */
  runnersYamlPath: string;
  /** The sysbuild domain/image used to resolve the path, if any. */
  sysbuildImage?: string;
} | undefined {
  const runnersYamlPath = resolveRunnersYamlPath(buildFolder, sysbuildImage);
  const parsed = parseRunnersYaml(runnersYamlPath);
  if (!parsed) { return undefined; }
  return {
    flashRunner: parsed.flashRunner,
    debugRunner: parsed.debugRunner,
    availableRunners: parsed.runners,
    runnersYamlPath,
    sysbuildImage,
  };
}
