/*
Copyright 2026 mylonics 
Author Rijesh Augustine

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * Parser for Zephyr's `<build>/zephyr/runners.yaml`. This file is generated by
 * the Zephyr build system and contains the canonical information needed to
 * flash and debug a build: ELF/HEX file names, GDB executable, the list of
 * available runners, the default debug/flash runner, and per-runner argument
 * lists.
 *
 * We use this as the source of truth for synthesizing cortex-debug debug
 * configurations on the fly so users no longer need to hand-maintain a
 * launch.json with cortex-debug specifics.
 */

import * as fs from "fs";
import * as path from "upath";
import * as yaml from "js-yaml";

/**
 * Parsed contents of runners.yaml. All fields are best-effort — the file may
 * be absent or partially populated depending on how far the build progressed.
 */
export interface RunnersYaml {
  /** Build directory recorded in the file (config.build_dir). */
  buildDir?: string;
  /** Board directory (config.board_dir). Useful for locating SVDs. */
  boardDir?: string;
  /** Absolute path to the ELF file (config.elf_file resolved against build dir). */
  elfFile?: string;
  /** Absolute path to the HEX file (config.hex_file resolved against build dir). */
  hexFile?: string;
  /** Absolute path to the BIN file (config.bin_file resolved against build dir). */
  binFile?: string;
  /** Absolute path to the GDB executable (config.gdb). */
  gdb?: string;
  /** Absolute path to OpenOCD if recorded (config.openocd). */
  openocd?: string;
  /** Optional OpenOCD search directories (config.openocd_search). */
  openocdSearch?: string[];
  /** All known runners (top-level `runners`). */
  runners: string[];
  /** The default flash runner (`flash-runner`). */
  flashRunner?: string;
  /** The default debug runner (`debug-runner`). */
  debugRunner?: string;
  /** Per-runner argument arrays (`args`). */
  args: { [runner: string]: string[] };
}

/** A single sysbuild domain as described in domains.yaml. */
export interface SysbuildDomain {
  name: string;
  buildDir: string;
}

/**
 * Read the sysbuild `domains.yaml` in a top-level build directory and return
 * the list of image domains. Returns undefined when `domains.yaml` does not
 * exist (i.e. the project is not using sysbuild).
 */
export function getSysbuildDomains(buildDir: string): SysbuildDomain[] | undefined {
  const domainsYamlPath = path.join(buildDir, "domains.yaml");
  if (!fs.existsSync(domainsYamlPath)) {
    return undefined;
  }
  try {
    const doc: any = yaml.load(fs.readFileSync(domainsYamlPath, "utf-8"));
    const domains: any[] = doc?.domains;
    if (Array.isArray(domains)) {
      return domains
        .filter((d: any) => typeof d?.name === "string" && typeof d?.build_dir === "string")
        .map((d: any) => ({ name: d.name as string, buildDir: d.build_dir as string }));
    }
  } catch {
    // ignore
  }
  return undefined;
}

/**
 * Resolve the path to runners.yaml for a build directory. Handles sysbuild by
 * delegating to the named domain (or default domain when omitted) via domains.yaml.
 *
 * Returns the absolute path even if the file does not exist; callers should
 * check existence themselves so they can produce a useful error.
 */
export function resolveRunnersYamlPath(buildDir: string, domainName?: string): string {
  const domainsYamlPath = path.join(buildDir, "domains.yaml");
  let effectiveBuildDir = buildDir;
  if (fs.existsSync(domainsYamlPath)) {
    try {
      const domainsDoc: any = yaml.load(fs.readFileSync(domainsYamlPath, "utf-8"));
      const targetName = domainName ?? domainsDoc?.default;
      const domains: any[] = domainsDoc?.domains;
      if (targetName && Array.isArray(domains)) {
        const targetDomain = domains.find((d: any) => d?.name === targetName);
        if (targetDomain?.build_dir) {
          effectiveBuildDir = targetDomain.build_dir;
        }
      }
    } catch {
      // fall through with original build dir
    }
  }
  return path.join(effectiveBuildDir, "zephyr", "runners.yaml");
}

/**
 * Parse a runners.yaml file. Returns undefined when the file does not exist or
 * cannot be parsed. Relative file paths inside `config.*_file` are resolved
 * against `config.build_dir/zephyr` to produce absolute paths.
 */
export function parseRunnersYaml(runnersYamlPath: string): RunnersYaml | undefined {
  if (!fs.existsSync(runnersYamlPath)) {
    return undefined;
  }
  let doc: any;
  try {
    doc = yaml.load(fs.readFileSync(runnersYamlPath, "utf-8"));
  } catch {
    return undefined;
  }
  if (!doc || typeof doc !== "object") {
    return undefined;
  }

  const config = (doc.config && typeof doc.config === "object") ? doc.config : {};
  const buildDir: string | undefined = typeof config.build_dir === "string" ? config.build_dir : undefined;
  const zephyrDir = buildDir ? path.join(buildDir, "zephyr") : path.dirname(runnersYamlPath);

  const resolveFile = (val: any): string | undefined => {
    if (typeof val !== "string" || !val) { return undefined; }
    return path.isAbsolute(val) ? val : path.join(zephyrDir, val);
  };

  const argsObj: { [runner: string]: string[] } = {};
  if (doc.args && typeof doc.args === "object") {
    for (const [runnerName, value] of Object.entries(doc.args)) {
      if (Array.isArray(value)) {
        argsObj[runnerName] = value.filter((v): v is string => typeof v === "string");
      }
    }
  }

  const runners: string[] = Array.isArray(doc.runners)
    ? doc.runners.filter((r: any): r is string => typeof r === "string")
    : [];

  return {
    buildDir,
    boardDir: typeof config.board_dir === "string" ? config.board_dir : undefined,
    elfFile: resolveFile(config.elf_file),
    hexFile: resolveFile(config.hex_file),
    binFile: resolveFile(config.bin_file),
    gdb: typeof config.gdb === "string" ? config.gdb : undefined,
    openocd: typeof config.openocd === "string" ? config.openocd : undefined,
    openocdSearch: Array.isArray(config.openocd_search)
      ? config.openocd_search.filter((s: any): s is string => typeof s === "string")
      : undefined,
    runners,
    flashRunner: typeof doc["flash-runner"] === "string" ? doc["flash-runner"] : undefined,
    debugRunner: typeof doc["debug-runner"] === "string" ? doc["debug-runner"] : undefined,
    args: argsObj,
  };
}

/**
 * Look for an SVD file in the board directory recorded in runners.yaml.
 * Returns the absolute path to the first `.svd` file found, or undefined.
 *
 * Zephyr boards occasionally ship an `.svd` file beside the board YAML; this
 * is a best-effort lookup so the cortex-debug peripheral viewer can be
 * populated automatically when one is present.
 */
export function findSvdFile(boardDir: string | undefined): string | undefined {
  if (!boardDir || !fs.existsSync(boardDir)) {
    return undefined;
  }
  try {
    const entries = fs.readdirSync(boardDir);
    for (const entry of entries) {
      if (entry.toLowerCase().endsWith(".svd")) {
        return path.join(boardDir, entry);
      }
    }
  } catch {
    // ignore
  }
  return undefined;
}

/**
 * Translate a Zephyr runner name to a cortex-debug `servertype`. Returns
 * undefined when the runner is not natively understood by cortex-debug.
 *
 * Notes:
 * - "stm32cubeprogrammer" uses STM32_Programmer_CLI, not the ST-LINK GDB
 *   server, so it cannot be mapped to cortex-debug's "stlink" type.
 * - "qemu" requires board-specific cpu/machine/serverpath that cannot be
 *   inferred generically; use a manual cortex-debug config for QEMU.
 */
export function runnerToServerType(runner: string): string | undefined {
  switch (runner) {
    case "jlink":
      return "jlink";
    case "openocd":
      return "openocd";
    case "pyocd":
      return "pyocd";
    case "stlink":
      return "stlink";
    case "blackmagicprobe":
    case "bmp":
      return "bmp";
    default:
      return undefined;
  }
}

/**
 * Read the `runners.yaml` in a build folder and return a lightweight hint
 * object for display in the UI. Returns undefined when the file does not exist
 * (i.e., the build has not been run yet).
 */
export function getRunnersYamlHint(buildFolder: string): {
  flashRunner?: string;
  debugRunner?: string;
  availableRunners: string[];
} | undefined {
  const runnersYamlPath = resolveRunnersYamlPath(buildFolder);
  const parsed = parseRunnersYaml(runnersYamlPath);
  if (!parsed) { return undefined; }
  return {
    flashRunner: parsed.flashRunner,
    debugRunner: parsed.debugRunner,
    availableRunners: parsed.runners,
  };
}
