on:
  push:
    branches:
      - develop
name: Push Extension Prerelease
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm --prefix server ci
      - run: npm --prefix client ci
      - run: npm version patch --no-git-tag-version
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "publish --pre-release -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          gh release create "v$VERSION" --prerelease --title "Prerelease $VERSION" -p "*.vsix"
